(require 'generic-x)

(define-generic-mode 'easy-seccomp-mode            
  '("//")                       
  '("")
  '(("@[A-Z_a-z][A-Z_a-z0-9]*" . 'font-lock-constant-face)
    ("#[[:space:]]*[_a-z][_a-z0-9]*[[:space:]]+[_A-Z][_A-Z0-9]*" . 'font-lock-preprocessor-face)
    ("#[[:space:]]*[_a-z][_a-z0-9]*[[:space:]]*" . 'font-lock-preprocessor-face)
    ("not in" . 'font-lock-keyword-face)
    ("in" . 'font-lock-keyword-face)
    ("=>" . 'font-lock-keyword-face)
    ("!=" . 'font-lock-keyword-face)
    ("==" . 'font-lock-keyword-face)
    ("<" . 'font-lock-keyword-face)
    ("<=" . 'font-lock-keyword-face)
    (">" . 'font-lock-keyword-face)
    (">=" . 'font-lock-keyword-face)
    ("&" . 'font-lock-keyword-face)
    ("&&" . 'font-lock-keyword-face)
    ("$syscall" . 'font-lock-variable-name-face)
    ("$arch" . 'font-lock-variable-name-face)
    ("$arg0" . 'font-lock-variable-name-face)
    ("$arg1" . 'font-lock-variable-name-face)
    ("$arg2" . 'font-lock-variable-name-face)
    ("$arg3" . 'font-lock-variable-name-face)
    ("$arg4" . 'font-lock-variable-name-face)
    ("$arg5" . 'font-lock-variable-name-face)
    ("[A-Z][A-Z_0-9]*(.*)" . 'font-lock-builtin-face))
  '("\\.easyseccomp$")
  nil
  "A mode for easy seccomp")
